### ISSUE TITLE
[BUG]-ZoomRoom SelectCamera() not working

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#1017]
**Was this bug identified in a specific build version?**
<= 1.12.0

**Describe the bug**
The SelectCamera(string key) method in ZoomRoom is not sending the command to select the camera by ID

**Expected behavior**
SelectCamera(string key) should send the command to select the camera by ID

**Comment by jtalborough** [comment]
@ndorin @andrew-welker Can we confirm this is closed

**Comment by jtalborough** [comment]
Closing
