### ISSUE TITLE
[FEATURE]-Show version information in Program File Name

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#1032]
**Is your feature request related to a problem? Please describe.**
It would be nice if the Program Name had the Essentials version number in it so it could be audited for compliance with PepperDash UDM

**Describe the solution you'd like**
The Program Name or File to have the version number included

**Comment by ndorin** [comment]
Any reason why UDM can't use the existing console command `reportverison` to determine the version number?  The base version number is also already reported by `progcomments` but we can't report the build type or number there.

**Comment by ngenovese11** [comment]
@jgutenplan for adding that functionality into UDM.  I'm not sure how it would work exactly... it might have to be its own compliance field

**Comment by jtalborough** [comment]
Upon discussion we think the issue is that UDM is not displaying the Essentials versions info (reportverisons) appropriately. The info is already provided by essentials. SO it really ends up being a lambda change.
Does this make sense @ngenovese11 @jgutenplan
