### ISSUE TITLE
[FEATURE]- Console Command to print all the available input/output port names for a given device key

### ISSUE THREAD

**Issue by mnchartier** [PepperDash/Essentials#1051]
**Is your feature request related to a problem? Please describe.**
I am having an issue getting the deviceKeys for audio and video inputs/outputs on a DMPS-3-300-C system to be used in TieLines and as the DefaultAudioKey.  I also believe that this Feature Request would be helpful for other devices also.

**Describe the solution you'd like**
Would like to have a Console Command that will print all the available input/output port names and keys for a given device.  For example all the video/audio input/outputs that are created when a DMPS processor is used.  This should ad in Configuration editing/creating.

**Describe alternatives you've considered**
I've gone through the code to see how each is being instantiated and still have a few AV input/outputs I can not get keys for to use in the configuration.

**Additional context**
I found how the video inputs and outputs devicekeys are set and are using them in the TieLines for a DMPS System as noted below. 
 {
                "sourceKey": "inRoomPc-1",
                "sourcePort": "anyVideoOut",
                "destinationKey": "processor-avRouting",
                "destinationPort": "inputCard1--HdmiIn1",
                "type": "audioVideo"
            },
            {
                "sourceKey": "wePresent-1",
                "sourcePort": "anyOut",
                "destinationKey": "processor-avRouting",
                "destinationPort": "inputCard2--HdmiIn2",
                "type": "audioVideo"
            },
            {
                "sourceKey": "processor-avRouting",
                "sourcePort": "outputCard1--hdmiOut1",
                "destinationKey": "Display-1",
                "destinationPort": "HdmiIn1",
                "type": "audioVideo"
            }

**Comment by ndorin** [comment]
It appears as though this console command already exists:

`getroutingports:[slotNumber] [deviceKey]`
