### ISSUE TITLE
[FEATURE]-ADD AM3200 Support

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#1072]
**Is your feature request related to a problem? Please describe.**
AM3200 support is not included in Essentials.  Current Airmedia devices use a class that inherits from and extend the Am3x00 class, and the Am3200 class inherits from and extends the Am3x00 class.

**Describe the solution you'd like**
Add am3200 to the AirmediaController Factory and change the base class of the Airmedia property to be am3x00 and use polymorphism to verify features present in the various classes.  There are some eventargs present in the Amx00 class that are not present in the am3x00 class, and the am3200 class is essentially just a inherit and rename from am3x00, so some of the event callback logic needs to be reworked.

**Describe alternatives you've considered**
Implement this device in SIMPL only

**Additional context**
This is required because of a specific client request.

**Comment by andrew-welker** [comment]
Closed in #1077
