### ISSUE TITLE
[FEATURE]-DM Endpoints need to report their number of inputs

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#1089]
**Is your feature request related to a problem? Please describe.**
We have the ability to use the same join maps for every endpoint (rx and tx) and can swap them out via Essentials config, but we don't get any actual data about the capabilities of the devices as far as number of ports is concerned

**Describe the solution you'd like**
One of two options :
1 - each input gets an HDCP Capability analog - if the hdcp capability == 0, then the device's port doesn't exist
2 - a count of all the InputPorts on the device - this could get problematic if we have an OSD or something similar, as in an AirMedia device, though that device has a different joinmap altogether and shouldn't be a concern

**Describe alternatives you've considered**
Leave the device in Simpl
Write a plugin to extend extant functionality

**Additional context**
Client Request

**Comment by andrew-welker** [comment]
Not all inputs on transmitters have HDCP, although those transmitters are probably becoming less and less common.

**Comment by TrevorPayne** [comment]
> Not all inputs on transmitters have HDCP, although those transmitters are probably becoming less and less common.

Correct, I accounted for this.  The count will only report inputs that DO have HDCP (HDMI, DisplayPort, and DM) - since those ports are always at the "head" of the line - it works out for cross referencing if you have 2 inputs that support HDCP, they are input 1 and 2.

It's not perfect, and I would liek to find a better way to do it long term, but I needed a solution quickly, and this works well enough in most cases.
