### ISSUE TITLE
[FEATURE]-Implment JoinMapBaseAdvanced for Fusion Attributes on FusionRoom and FusionStaticAsset instances

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#109]
**Is your feature request related to a problem? Please describe.**
Fusion implementation for standalone Essentials rooms currently uses a static join mapping for attributes

**Describe the solution you'd like**
Take the current static mapping and break it out into a class that derives from JoinMapBaseAdvanced and make it the default map unless a custom join map is specified in config

**Additional context**
Need to add the necessary config properties to specify a custom join map for a FusionRoom and FusionStaticAsset

**Comment by andrew-welker** [comment]
see #535 and associated PR #557
