### ISSUE TITLE
[Documentation]-Type necUniversal doesn't exist

### ISSUE THREAD

**Issue by derek555** [PepperDash/Essentials#120]
**Describe the bug**
On wiki page: https://github.com/PepperDash/Essentials/wiki/ConfigurationStructure
In section : Device Object Structure

_type": Think of this as a way to identify what specific module you might associate with this device.  In Essentials, this value is used to determine what class will be instantiated for the device (ex. "necUniversal" or "samsungMdc" for two types of displays)_

**Expected behavior**
Remove necUniversal as an example or replace it with necmpsx.

**Comment by andrew-welker** [comment]
I've updated the page. Thanks for letting us know!
