### ISSUE TITLE
[BUG]- CommFactory.CreateCommForDevice can't be called in device factory methods or in a device's constructor

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#126]
**Describe the bug**
If the communication method is "com" and needs a com port not present on the control system it's possible that we won't be able to retrieve the parent device containing the port (DM endpoint, CEN-COM-3, NVX, etc.) if that device hasn't been constructed yet.

This wouldn't be an issue with any other communication type or when using ports on the control system which might explain why we haven't encountered this previously.

**Expected behavior**
May need to move the CommFactory.CreateCommForDevice method call to one of the activation phases (probably a post activation action) to resolve.

Originally reported by @jtalborough

**Comment by andrew-welker** [comment]
Seems to me this'd best be solved by moving the actual linking of the port to a post-activation method on the ComPortController. Maybe we can add a constructor where the ComPort parameter is replaced by Func<EssentialsControlPropertiesConfig, ComPort>, and an additional parameter for the config and that Func is added as a post-activation method for the coms. We should probably consider doing something similar for the CecPortController as well, as the same issue may present itself there.
