### ISSUE TITLE
[BUG]-1.5.0-rc-138 Issue with Bridge post activation 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#129]
**Describe the bug**

**Stacktrace**

Include a stack trace of the exception if possible.
```
[10:12:14.000]App 2:[Cameras-Bridge] ERROR: Device PostActivation failure:
System.InvalidProgramException: InvalidProgramException
   at PepperDash.Essentials.Bridges.EiscApi.<.ctor>b__0()
   at PepperDash.Core.Device.<PostActivate>b__2(Action a)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at PepperDash.Core.Device.PostActivate()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.InitializeSystem()
   at Crestron.SimplSharpPro.CrestronControlSystem.InitializeSimplSharpProApplication()
   at Crestron.SimplSharpProInternal.SimplSharpProManager.LoadSimplSharpProApplication(String moduleFileName)
   at Crestron.SimplSharpProInternal.SimplSharpProManager..ctor(UInt32 appNumber, String simplSharpProAppName, UInt32 flags, Boolean& badExit)
   at Crestron.SimplSharpProEntry.b(String[] A_0)
```

**Additional context**
Implementing IBridge 

``` json


            {
                "group": "cameras",
                "key": "Camera01",
                "name": "Main Camera",
                "properties": {
                      "control": {
                        "comParams": {
                            "baudRate": 115200,
                            "dataBits": 8,
                            "hardwareHandshake": "None",
                            "parity": "None",
                            "protocol": "RS232",
                            "softwareHandshake": "None",
                            "stopBits": 1
                        },
                        "controlPortDevKey": "processor",
                        "controlPortNumber": 5,
                        "method": "com"
                    },
                    "presets": [
                        {
                            "id": 1,
                            "name": "Wide"
                        },
                        {
                            "id": 2,
                            "name": "Zoom"
                        }
                    ]
                },
                "type": "panasonicHttpCamera",
                "uid": 1010
            },
            {
                "group": "api",
                "key": "Cameras-Bridge",
                "name": "eisc-DSP",
                "properties": {
                    "control": {
                        "ipid": "D6",
                        "method": "ipidTcp",
                        "tcpSshProperties": {
                            "address": "127.0.0.2",
                            "port": 0
                        }
                    },
                    "devices": [
                        {
                            "deviceKey": "Camera01",
                            "joinStart": 1
                        }
                    ]
                },
                "type": "eiscApi",
                "uid": 4
            }
```

**Comment by andrew-welker** [comment]
@jtalborough Can you post your configuration for the bridge that's failing? Also, which interface are you implementing in your plugin: IBridge or IBridgeAdvanced?

**Comment by andrew-welker** [comment]
One more request: Can you post your LinkToApi method from the device class that's failing?

**Comment by jtalborough** [comment]
#region IBridge Members

        public void LinkToApi(Crestron.SimplSharpPro.DeviceSupport.BasicTriList trilist, uint joinStart, string joinMapKey)
        {
            this.LinkToApiExt(trilist, joinStart, joinMapKey);
        }

        #endregion

**Comment by andrew-welker** [comment]
Remove IBridge from your Panasonic Camera controller class and change your LinkToApi method to add a EiscApiAdvanced parameter at the end. See the example below. CameraBase inherits from EssentialsBridgeableDevice, which implements IBridgeAdvanced, and is getting caught in the if statement first.

`public void LinkToApi(BasicTriList trilist, uint JoinStart, string joinMapKey, EiscApiAdvanced bridge)`

You can keep the rest of the method the same.

**Comment by ngenovese11** [comment]
isn't this a breaking change for everything that inherits from CameraBase now?

**Comment by andrew-welker** [comment]
It is. I'll look at how to make it backwards compatible prior to release.

**Comment by ndorin** [comment]
> isn't this a breaking change for everything that inherits from CameraBase now?

You'll note that the version here has an incremented minor version, which means that it's a significant update.  That means there may be some more fundamental changes that require updates to plugins to maintain compatibility.  Maintaining perfect backwards compatibility is not always possible and while we try our best to do it where it makes sense, there will be situations where plugins will be affected and will need to be updated to be compatible with newer versions of the framework.

**Comment by ngenovese11** [comment]
Indeed, just making sure I'm aware so that I can keep my plugins up to date

**Comment by andrew-welker** [comment]
Got a fix in the works for this that should be backwards compatible. Look for a new RC in a couple of hours.

**Comment by ngenovese11** [comment]
you the man!

**Comment by andrew-welker** [comment]
CameraBase is moved back to an EssentialsDevice, and each internal implementing class now implements IBridgeAdvanced. There is a protected method on CameraBase now called LinkCameraToApi that, if you are planning on using the standard join map and linking logic, can be called to do that.
