### ISSUE TITLE
[BUG]-1.5.0-rc-139 will not load plugin type 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#133]
**Describe the bug**
Cannot load a plugin using the new plugin load methods in v 1.5.0-rc-139 in v1.4.35-alpha-119 loads fine. 

**Stacktrace**

Include a stack trace of the exception if possible.
```
[15:59:13.000]App 2:Loaded assembly 'PresetsEpi', version 1.0.0.25412
[15:59:13.000]App 2:All Plugins Loaded.
[15:59:19.000]App 2:ERROR: Cannot load unknown device type 'Presets', key 'Presets'.
```

**Plugin Source**
https://github.com/PepperDash-Engineering/epi-utilities-presets/commit/84ed18ef5a682dc62fc4505df2727c5131dd37da

[Program2.zip](https://github.com/PepperDash/Essentials/files/4548310/Program2.zip)

**Additional context**

**Comment by andrew-welker** [comment]
@jtalborough Do you see a message in console similar to below?

![image](https://user-images.githubusercontent.com/1765622/80537342-2099ba00-8961-11ea-9747-a41a1fac4359.png)

**Comment by andrew-welker** [comment]
This is cause by the way we are checking the plugin's specified minimum supported version. I've updated the method, and a new RC build will be available once the PR is merged in.
