### ISSUE TITLE
[FEATURE]-Add CI Pipeline to test Essentials Versions

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#140]
**Is your feature request related to a problem? Please describe.**
Specifying the minimum version in Essentials does not integrate with the pipeline

**Describe the solution you'd like**
Have the CI pipeline checkout the Minimum Version specified and build the solution, and also possibly check out all subsequent release builds

**Describe alternatives you've considered**
None

**Additional context**
Publishing the build results may not be necessary, but confirming that your plugin _builds_ with essentials versions would be helpful.  Obviously that doesn't guarantee everything works, but its a start towards confirming compatibility.

**Comment by ngenovese11** [comment]
@jtalborough for visibility

**Comment by andrew-welker** [comment]
I'm not sure what you're requesting here. Do you want the Action in the plugin template repo

**Comment by ngenovese11** [comment]
closing issue as this feature is pertaining to plugin build actions not Essentials
