### ISSUE TITLE
[BUG]-DeviceManager.AddDevice() potentially unsafe

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#147]
**Describe the bug**

If you happen to call DeviceManager.AddDevice() in a PreActivate/CustomActivate/PostActivate it will throw an Exception since you are trying to add to the Devices dictionary while currently iterating through it in the DeviceManager.ActivateAll() method.  This causes the base ControlSystem.Initialize() method to fail leaving everything in an inconsistent state.

**Stacktrace**

[08:20:18.000]App 2:FATAL INITIALIZE ERROR. System is in an inconsistent state:
System.InvalidOperationException: InvalidOperationException
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.Enumerator.MoveNext()
   at PepperDash.Essentials.Core.DeviceManager.ActivateAll()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.InitializeSystem()
   at Crestron.SimplSharpPro.CrestronControlSystem.InitializeSimplSharpProApplication()
   at Crestron.SimplSharpProInternal.SimplSharpProManager.LoadSimplSharpProApplication(String moduleFileName)
   at Crestron.SimplSharpProInternal.SimplSharpProManager..ctor(UInt32 appNumber, String simplSharpProAppName, UInt32 flags, Boolean& badExit)
   at Crestron.SimplSharpProEntry.b(String[] A_0)

**To Reproduce**
- Call AddDevice() in any of the methods: PreActivate/CustomActivate/PostActivate
- If you call CommFactory.CreateComForDevice() it adds the comm port to the device manager, throwing an error

**Expected behavior**
Two possible solutions, 

1) Add the following which _should_ iterate through a copy of the Dictionary as opposed to the original collection.

```csharp
// PreActivate all devices
            foreach (var d in Devices.Values.ToList())
            {
                try
                {
                    if (d is Device)
                        (d as Device).PreActivate();
                }
                catch (Exception e)
                {
                    Debug.Console(0, d, "ERROR: Device PreActivation failure:\r{0}", e);
                }
            }
```

2) Block the AddDevice() method from adding to the collection once the Activation phase has started because presumably we don't want to add any devices mid-activation.
 
**Screenshots**

**Additional context**

**Comment by andrew-welker** [comment]
What's the intention behind adding devices to the Device Manager in this manner?

**Comment by ngenovese11** [comment]
There really shouldn't be I wouldn't think... but it is common for devices to instantiate add other devices to the DeviceManager, its just typically been done in the constructor.  If we don't want to be adding devices once the Activation phase starts, we should at least throw an error instead of failing the entire Initialization method and putting the proc in a failed state

**Comment by andrew-welker** [comment]
I just went through and added a CCriticalSection to the DeviceManager class, and added it to pretty much all the methods in the class. Not sure there's any reason to really send a message, but that could be done relatively easily. Try alpha-165 when it's posted and see if it at least keeps the exception from happening.

**Comment by andrew-welker** [comment]
@ndorin and I discussed this. We've gone through and added a critical section and used it in any methods that modify the DeviceManager dictionary. We've also added a public boolean field called AddDevicesEnabled. Once the activation sequence has run, this will be set to false. If the AddDevice method is called after the activation sequence is complete, a message indicating that adding devices isn't allowed will be printed to console and logged in the error log. Please test this with build alpha-166 when it's available.

**Comment by ngenovese11** [comment]
Will do, thanks for looking into it!
