### ISSUE TITLE
[BUG]-Cannot load dmTx in latest RC (v1.5.0-rc-148)

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#151]
**Describe the bug**
Cannot load dmtx4k100 in latest version of Essentials v1.5.0-rc-148. 

[14:45:25.000]App 2:Creating device 'dmTx01', type 'dmtx4k100'
[14:45:25.000]App 2:ERROR: Cannot load unknown device type 'dmtx4k100', key 'dmTx01'.

Works fine on older rev. 

[configurationFile - Copy.txt](https://github.com/PepperDash/Essentials/files/4588895/configurationFile.-.Copy.txt)

**Comment by ndorin** [comment]
Did you run the gettypes console command? You may need to use the full type name now where previously just the prefix would work.

**Comment by ndorin** [comment]
I’m guessing you may need dmtx4k100c

**Comment by jtalborough** [comment]
Yup that works. We may need a memo.
