### ISSUE TITLE
[BUG]-The method JoinMapHelper.GetJoinMapBase(string) has been removed in latest release. 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#152]
**Describe the bug**
Some plugins rely on this method. Can we get this method added back in and marked as deprecated. 

<img width="1107" alt="Screen Shot 2020-05-06 at 3 33 28 PM" src="https://user-images.githubusercontent.com/3274657/81220436-4b15f380-8faf-11ea-8f52-1b66929ff9df.png">

**Comment by andrew-welker** [comment]
Please try hotfix-174 and let me know if if fixes the issue. If it does, we'll get it into a new release shortly.

**Comment by alex-johnson** [comment]
I don't see hotfix-174 on builds repo yet. I did built that version and tested, so far it looks good.
