### ISSUE TITLE
[FEATURE]-Add IHasVideoMute interface

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#178]
**Is your feature request related to a problem? Please describe.**
When interacting with devices I'd like an interface to check if the device supports video mute, similar to IPower, IHasVolumeWithFeedback

**Describe the solution you'd like**
An interface that defines VideoMuteOn, VideoMuteOff, and VideoMuteToggle methods along with a VideoMuteIsOn BoolFeedback

**Describe alternatives you've considered**
Using PowerOff/PowerOn is possible but I have clients that prefer to mute over powering off.  Also certain projectors may have lengthy warmup/cooldown times

**Comment by jtalborough** [comment]
+1 this is needed.
