### ISSUE TITLE
[FEATURE]-Add IHasTrilist Interface

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#180]
**Is your feature request related to a problem? Please describe.**
While writing my trilist middleware plugin I realized that utilizing only an interface that exposes SmartObjects would limit it to only working with full panels.  Adding this new interface will allow me to work with button panels as well.

**Describe the solution you'd like**
Add a new Interface that only requires implementation of BasicTrilist.

**Comment by andrew-welker** [comment]
Are you sure? Most button-only panels that I'm aware of implement a different interface. I think it's IButtons or something to that effect for the buttons.

**Comment by andrew-welker** [comment]
Closing this issue as it's not necessary at this point in time.
