### ISSUE TITLE
[FEATURE]-Add HD-MD HDMI switchers to Essentials

### ISSUE THREAD

**Issue by jkdevito** [PepperDash/Essentials#186]
**Is your feature request related to a problem? Please describe.**
Request to add HD-MD HDMI switchers, to include HD-MD4x1-4K-E and HD-MD4x2-4K-E, to Essentials. 

**Describe the solution you'd like**
Needs to be added to Essentials as a valid switcher

**Comment by TrevorPayne** [comment]
Look like the 4x1 is in there, but the class needs some love.

**Comment by andrew-welker** [comment]
Looks to me like the controller class is built to handle either version of the HD-MD series, but it does need some love. @TrevorPayne , are you going to pick this up and work on it?

**Comment by TrevorPayne** [comment]
@andrew-welker Yeah - may not be until next week though - I don't think this request is immediately urgent, though it is necessary.

The class as written wouldn't fully support the 4x2 because it only adds a single output port, so it breaks for essentials routing as is.  I may hit it this evening.

**Comment by andrew-welker** [comment]
@TrevorPayne Ok. I've assigned it to you for now. I might pick it up if I get a chance before next week. We'll see.

**Comment by TrevorPayne** [comment]
@andrew-welker I'm jumping into this now.  I'll commit *something* by EOD though.
