### ISSUE TITLE
[FEATURE] - Add a way to route using numeric values instead of instances of IRouteInput/IRouteOutput

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#192]

**Comment by andrew-welker** [comment]
The best way (and the agreed on idea) is to create an interface that has an `ExecuteSwitchNumeric` method. The `ExecuteSwitchNumeric` method should take 2 ints, and an eRoutingSignalType.  This interface will be implemented on the existing Dm Chassis controller classes.

**Comment by ndorin** [comment]
We should add a new interface called `IRoutingNumeric` that inherits from IRouting and adds `void ExecuteNumericSwitch(ushort input, ushort output, eRoutingSignalType type);`

Then the existing `IRmcRouting` and `ITxRouting` should inherit from the new `IRoutingNumeric`

**Comment by jtalborough** [comment]
Since its primary use is Simpl I think it make sense to use 3 ints rather than 2 ints and an eNum. 
Ideally we offer both options using overrides.

**Comment by ndorin** [comment]
@jtalborough The existing implementation should be followed for consistency and since we don't expose the eRoutingSignalType arguement to the bridge and it's handled in the bridge logic, it doesn't need to be abstracted to a number.
