### ISSUE TITLE
Document process for clearing routings using the ExecuteSwitch method from IRouting

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#193]

**Comment by andrew-welker** [comment]
In most cases, this will be done by setting the inputSelector parameter as null.

**Comment by TrevorPayne** [comment]
If I recall correctly, since we utilize 'CrestronCollection' for inputs and outputs, attempting to set a '0' should work as well.  It attempts to get a [0] index which doesn't exist and returns null, thus setting the object to the desired value.
