### ISSUE TITLE
[FEATURE]-JoinMetadata information isn't clear

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#198]
**Is your feature request related to a problem? Please describe.**
The JoinMetadata properties are unclear in their usefulness.  Changes should be made in the properties to more clearly define what the metadata wishes to communicate.

**Describe the solution you'd like**
  It may be beneficial to change the "Label" property to "Name" and add a "Description" property, to make the portions of metadata more clear.

**Describe alternatives you've considered**
Currently, I have been using "Label" as if it were "Description"

**Additional context**
Simply changing "Label" to "Description" wouldn't be enough, because we can use the "Name" property to link data in the trilist to other things by key.

**Comment by andrew-welker** [comment]
We should also find a way to include information about how digital joins are expected to behave from SIMPL. For instance, does it need to be held high, is a pulse ok, etc.

**Comment by TrevorPayne** [comment]
That's at least 2 more metadata portions.  Something like `eToSimplBehavior` and `eFromSimplBehavior`

I'm not sure I like that - because it's a hell of a lot of change to go back and make, and then it's really only applicable for digital joins.
