### ISSUE TITLE
[FEATURE]-Allow PluginFactory to return IEnumerable<EssentialsDevice>

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#199]
**Is your feature request related to a problem? Please describe.**
Many times a plugin is a collection of devices.  Often these devices are built within the constructor of the "main plugin" and added to the device manager.  Returning a collection of devices would allow for multiple devices to be built and added within the factory and injected into whichever devices necessary, as opposed to having an overly complex Device constructor whose sole purpose is building many other devices.

**Describe the solution you'd like**
A way to return multiple EssentialsDevices via the PluginFactory

**Describe alternatives you've considered**
Adding devices within the BuildDevice method

**Comment by andrew-welker** [comment]
More likely the return type would be `IEnumerable<KeyValuePair<string,IKeyed>>` to allow for relatively easily adding the devices to the DeviceManager Dictionary. The difficulty is in differentiating between the 2 factory methods and calling the right one when the system starts up.

**Comment by ndorin** [comment]
@ngenovese11 can you provide an example of this in context?  Typically each device item in the config array instantiates a single device.  In some cases that device is responsible for instantiating sub devices and adding them to the DeviceManager.  I'm struggling to see a scenario where it would make sense to return a collection of devices.

**Comment by ngenovese11** [comment]
the biamp/qsc plugin every fader and control point is a device added to device manager

**Comment by ndorin** [comment]
@ngenovese11 I would question whether all control points for DSPs should be added to the device manager rather than just the main DSP controller class and provide a means by which to access the sub devices via the controller.

**Comment by ngenovese11** [comment]
Plugin design aside... DeviceManager.AddDevice() is a already a public method; this would simply allow for cleaner usage of an existing feature.

**Comment by TrevorPayne** [comment]
@ngenovese11 - The DSP Controller Class does that per your direction.  You may not remember, but the Tesira Plugin was modified to do that after a conversation with you about what needed to be done in order to make it essentials compliant.

**Comment by ndorin** [comment]
Ok, at this point it's not feasible to allow the PluginFactory's BuildDevice method to return a collection of devices. However, we can add a method to DeviceManager called AddDevices(IEnumerable<IKeyed> devices) that would accept a collection of IKeyed.  It would be the responsibility of the parent device (DSP wrapper device or other) to add all it's child devices within it's constructor so that all the child devices are already in the DeviceManager and ready for activation.
