### ISSUE TITLE
Add some device config detail with example snippets. Maybe link to Example Configs in repo

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#20]

**Comment by TrevorPayne** [comment]
I've added a few things to documentation and am interested in getting some feedback on the work that has been done before I continue further with updates.

https://github.com/PepperDash/Essentials/wiki/Bridging-To-Hardware-Resources
https://github.com/PepperDash/Essentials/wiki/GenericComm
https://github.com/PepperDash/Essentials/wiki/RelayOutput
https://github.com/PepperDash/Essentials/wiki/DigitalInput

@ndorin 
@andrew-welker

**Comment by ndorin** [comment]
I’ll have a look at the wiki additions in the morning. In terms of config snippets, the goal we’d like to work towards is for each device to define its own config snippet in code as an attribute on the class. Then we can use a console command (Eg. getdeviceconfigsnippet) that takes a typename and returns the snippet from that device class. Same mechanism that we use to return the description attribute currently for the gettypes console command.

**Comment by TrevorPayne** [comment]
I'd be interested in talking to you about what this would look like.  I'm absolutely willing to take this on as a self-documented feature in Essentials

On May 13, 2020 11:44 PM, Neil Dorin <notifications@github.com> wrote:

I’ll have a look at the wiki additions in the morning. In terms of config snippets, the goal we’d like to work towards is for each device to define its own config snippet in code as an attribute on the class. Then we can use a console command (Eg. getdeviceconfigsnippet) that takes a typename and returns the snippet from that device class. Same mechanism that we use to return the description attribute currently for the gettypes console command.
