### ISSUE TITLE
[BUG]-Some DM TX Bridge functionality isn't working

### ISSUE THREAD

**Issue by andrew-welker** [PepperDash/Essentials#200]
The joins for Freerun, and individual input video sync don't do what they're supposed to do

**Comment by andrew-welker** [comment]
I added a subscription to the VgaInput.StreamInputChange event and fired updates for both Free Run and VGA input sync there in the DM-Tx-200-C-2G controller class. Also added logic to fire feedback updates for HDMI input sync to the HdmiInput.StreamInputChange handler.

Once @ediablo80 verifies operation, the fixes will get propogated to the rest of the transmitter classes as necessary by either @TrevorPayne or myself.

**Comment by TrevorPayne** [comment]
@ediablo80 told me that it all works well - I would have liked to get a confirmation within the issue, but hopefully a screenshot of the ![confirmation](https://user-images.githubusercontent.com/44117050/82473585-68f35600-9a8f-11ea-8ddc-ed2f1f7100c4.PNG) will work.

**Comment by ediablo80** [comment]
Confirmed "Enable Free Run" digital signal, including feedback, on Bridge correctly adjusted Free Run as verified by DM Tools on the DM-TX. Changing this property in DM Tools also updated the feedback on the Bridge. 
One slight caveat is that "Enable Free Run" as defined by the bridge has opposing digital properties with the "Disable Free Run" that is exposed in DM Tools (when Enable Free Run is high, Disable Free Run checkbox is unchecked). This behavior is correct though.

Testing DM-TX Video Input02 Sync Fb (VGA input on a DM-TX-200-C) now works as expected
