### ISSUE TITLE
[FEATURE]-Occupancy change in Fusion Rooms should send a string

### ISSUE THREAD

**Issue by andrew-welker** [PepperDash/Essentials#226]
Based on information from Crestron, the boolean signals on an Occupancy Sensor Fusion Asset (remote or local) are used for logging, and the string value is used for scheduling panels. As such, we should modify the Fusion controller to send the required string when occupancy changes.

**Comment by TrevorPayne** [comment]
Replicated the data WRT RemoteOccupancy tracking from the Fusion SSI implementation.
