### ISSUE TITLE
DmBladeChassis EndpointOnlineFeedback and Endpoint Com access not working

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#23]
So far in tests with DM-MD64X64 blade chassis, the EndpointOnlineFeedback property to determine if a DM-RMC device is online does not report the correct value.

Also, we've been unable to get COM ports on DM-TX or DM-RMC devices to work when attached to a blade chassis.  

Both issues have been reported to Crestron and acknowledged as FW issues on the blade chassis.

New FW should resolve this issue.

**Comment by andrew-welker** [comment]
Do we need to keep this issue open? I'm thinking we can close for now and reopen when/if the firmware is updated.

**Comment by ndorin** [comment]
Keep it open. This should be visible to the public in case they encounter the issue.

Sent from my iPhone

On Sep 3, 2020, at 5:12 PM, Andrew Welker <notifications@github.com> wrote:

﻿

Do we need to keep this issue open? I'm thinking we can close for now and reopen when/if the firmware is updated.
