### ISSUE TITLE
[FEATURE]-Consolidate Enable/Disable joins in HdMdNxM4kEControllerJoinMap

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#232]
**Is your feature request related to a problem? Please describe.**
We have dupicate joins for Enable and Disable Auto Route

**Describe the solution you'd like**
Remove DisableAutoRoute and make it a Hold high to enable, release to disable.

**Describe alternatives you've considered**
No Alternatives Exist

**Comment by andrew-welker** [comment]
What do the symbols for these devices have on them in SIMPL?

**Comment by andrew-welker** [comment]
The SIMPL Windows symbols have separate enable/disable joins on them, which leads me to think that we need to keep that paradigm for easier drop-in of Essentials to existing systems that have the HD-MD series in them. Thoughts?
![image](https://user-images.githubusercontent.com/1765622/83916746-ef1bc780-a732-11ea-9d76-722262b08e04.png)

**Comment by TrevorPayne** [comment]
This is a rarely used device for us - and it would negatively impact the allocated space for the joinMap.  I'll do either, but I think that a held "high" for enable and a drop for disable would be appropriate.

**Comment by andrew-welker** [comment]
Ok. Go ahead and make the change.
