### ISSUE TITLE
[BUG]-Both EiscApi and EiscApiAdvanced should support bridging to any device that supports IBridge or IBridgeAdvanced

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#237]
**Describe the bug**
When using an An EiscBridgeAdvanced with a legacy device that supports IBridge the linking exceptions hits an exception. The EiscBridgeAdvanced should support iBridge. This is essential for backwards compatibility.

**Comment by andrew-welker** [comment]
At this moment, this isn't possible. `IBridge` is in PepperDash.Essentials and is in the main Essentials assembly, while `IBridgeAdvanced` is in PepperDash.Essentials.Core and is in the same assembly as `EiscApiAdvanced`. Having EiscApiAdvanced reference `IBridge` and handle them would cause a circular reference.

Currently, the best way to handle this when mixing legacy and new plugins is to use `EiscApi`. In the new plugins that implement `IBridgeAdvanced`, add a null check for the bridge device. If it's not null, add the joinMap to it, other wise continue on as normal. Devices using JoinMapAdvanced will still link up correctly to the bridge, while eliminating the exception.

`public void LinkToApi(...EiscApiAdvanced bridge)
{
 //do stuff here
    if(bridge != null)
    {
        bridge.AddJoinMap(joinMap);
    }

//link stuff here
}`

**Comment by ngenovese11** [comment]
What functionality do we lose if we don’t use EISC API advanced?


____________________________
Nick Genovese
Software Developer
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>

Email: ngenovese@pepperdash.com<mailto:ngenovese@pepperdash.com>
Direct: 617.206.9812
Toll free: 800.377.9112 x444
Fax: 617.208.0124

Introducing PepperDash Portal™<http://www.pepperdash.com/products/portal/>, the first and only AV Standards Management Platform.

**Comment by andrew-welker** [comment]
Printing out join maps using a console command.

**Comment by andrew-welker** [comment]
After discussion with @ndorin & @jtalborough, I implemented a fix for this. There's an added `IBridge` interface in the `PepperDash.Essentials.Core` namespace, and the `IBridge` interface in `PepperDash.Essentials` inherits from this one. `EiscApiAdvanced` now will accept either bridge type. When the bridge is `IBridge`, a notice will be logged to the Error Log.

**Comment by andrew-welker** [comment]
@jtalborough discovered an issue with this fix and older plugins (#258 for stack traces) using the `IBridge` interface. @ndorin and I discussed the issue, and we'll be reverting the fix made in PR #253  here. One thing we want to figure out before we do is how to let developers know if they're using `EiscApiAdvanced` with incompatible plugins.

One other question is whether `IBridge` should ONLY work with `EiscApi` and `IBridgeAdvanced` should ONLY work with `EiscApiAdvanced`.

**Comment by andrew-welker** [comment]
> @jtalborough discovered an issue with this fix and older plugins (#258 for stack traces) using the `IBridge` interface. @ndorin and I discussed the issue, and we'll be reverting the fix made in PR #253 here. One thing we want to figure out before we do is how to let developers know if they're using `EiscApiAdvanced` with incompatible plugins.
> 
> One other question is whether `IBridge` should ONLY work with `EiscApi` and `IBridgeAdvanced` should ONLY work with `EiscApiAdvanced`.

After some thought, my proposed solution is to make `EiscApiAdvanced` work ONLY with `IBridgeAdvanced` and `EiscApi` work ONLY with `IBridge`. If you have plugins that have mixed implementations, there are 2 ways forward: segregate them on different EISC's/bridges, or modify the plugins to implement both `IBridge` and `IBridgeAdvanced`. 

If a plugin implements the wrong interface for the bridge, a warning will be printed to console AND to the error log.

Please respond here for further discussion.

**Comment by ngenovese11** [comment]
Have all Essentials Devices (DM) _only_ implement IBridgeAdvanced at this point?  If so then all existing configs would need to be updated before moving Essentials forward as they would all be using EiscApi to bridge to existing devices

**Comment by andrew-welker** [comment]
Yes. All internal Essentials Devices are IBridgeAdvanced only. I can look into making DM devices implement IBridge as well, but that may result in a circular reference again.

**Comment by ngenovese11** [comment]
Understood

Nick Genovese
Developer
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>
240.888.6090

PepperDash Mobile Control<http://www2.pepperdash.com/learn-about-mobile-control>™ - BYOD Crestron Control, no special app required

**Comment by andrew-welker** [comment]
After discussion with @jtalborough, we came down on a couple of things.

1. I'm going to revert to bridging as it exists in 1.5.5: `EiscApi` will support both `IBridge` and `IBridgeAdvanced`. `EiscApiAdvanced` will support `IBridgeAdvanced` ONLY. 
2. All internal Essentials Devices need to have a null check on the bridge device that is passed to the `LinkToApi` method. This will prevent current installations that are running an older version of Essentials from throwing a null reference error when/if Essentials is upgraded and the config is not changed or updated. If the bridge is null, a message will be printed to console at debug level 0 prompting an upgrade of the config to the new method.
