### ISSUE TITLE
Possible .dll conflicts when using .cplz files to load plugins

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#24]
If using plugins and using the .cplz package in the plugin folder on a processor, there can be conflicts with different versions of .dll assemblies that are either shared by the framework or between multiple plugins.

The current workaround is to only put the .dlls specific to your plugin in the plugin folder and not use the .cplz file.

We're working on a new feature that will try to track what assemblies are already loaded and not load duplicates of the same .dll.

**Comment by bitm0de** [comment]
Within a single appdomain, the CLR will allow multiples of the same assembly to be loaded as long as they are **strongly named** and the **assembly version is different**. I've found that you can still do this with the `AssemblyKeyFileAttribute` though.

```
#pragma warning disable 1699
[assembly: AssemblyKeyFileAttribute(<keyfile>)]
#pragma warning restore 1699
```
