### ISSUE TITLE
[FEATURE]- Support for internal RFGateway

### ISSUE THREAD

**Issue by jonavila** [PepperDash/Essentials#261]
**Is your feature request related to a problem? Please describe.**
I noticed that there doesn't seem to be support for internal RF Gateways like the one found in an MC3 processor. I wanted to try out Essentials on an MC3 and was about to start creating my first plugin for CLW-DIMEX/SWEX lighting devices, but noticed the lack internal gateway support in this code:
https://github.com/PepperDash/Essentials/blob/release/1.5.6/essentials-framework/Essentials%20Core/PepperDashEssentialsBase/Gateways/CenRfgwController.cs

**Describe the solution you'd like**
Add support for internal gateways out of the box

**Describe alternatives you've considered**
I will attempt to create a plugin for the internal RF gateway

**Additional context**
Thanks for such an awesome project. Hopefully, I can start using it for my home system.

**Comment by TrevorPayne** [comment]
@jonavila It's supported by default if you have your processor set as an MC3 - any device that would register to an RF Gateway, you set the parent device as the MC3.  No need to set up a secondary gateway device.

**Comment by TrevorPayne** [comment]
@jonavila 

As an example, take a look at the Preactivation region for PepperDash.Essentials.Core.Hrxx0WirelessRemoteController

`#region Preactivation

        private static Hr1x0WirelessRemoteBase GetHr1x0WirelessRemote(DeviceConfig config)
        {
            var props = JsonConvert.DeserializeObject<CrestronRemotePropertiesConfig>(config.Properties.ToString());

            var type = config.Type;
            var rfId = (uint)props.Control.InfinetIdInt;

            GatewayBase gateway;

            if (props.GatewayDeviceKey == "processor")
            {
                gateway = Global.ControlSystem.ControllerRFGatewayDevice;
            }
            else
            {
                var gatewayDev = DeviceManager.GetDeviceForKey(props.GatewayDeviceKey) as CenRfgwController;
                if (gatewayDev == null)
                {
                    Debug.Console(0, "GetHr1x0WirelessRemote: Device '{0}' is not a valid device", props.GatewayDeviceKey);
                    return null;
                }
                Debug.Console(0, "GetHr1x0WirelessRemote: Device '{0}' is a valid device", props.GatewayDeviceKey);
                gateway = gatewayDev.GateWay; 
            }

            if (gateway == null)
            {
                Debug.Console(0, "GetHr1x0WirelessRemote: Device '{0}' is not a valid gateway", props.GatewayDeviceKey);
                return null;
            }

            switch (type)
            {
                case ("hr100"):
                    return new Hr100(rfId, gateway);
                case ("hr150"):
                    return new Hr150(rfId, gateway);
                case ("hr310"):
                    return new Hr310(rfId, gateway);
                default:
                    return null;
            }
        }`

**Comment by jonavila** [comment]
Thanks @TrevorPayne. Totally missed that
