### ISSUE TITLE
[BUG]-Registration of Hrxx0WirelessRemoteController missing

### ISSUE THREAD

**Issue by jonavila** [PepperDash/Essentials#262]
**Describe the bug**
I was able to successfully configure a HR-150 remote with version 1.5.6, but I can't seem to find where the device's register method is actually called if the gateway used has deviceKey "processor". Is it possible that the current device assumes that the gateway's Register method will be called? That certainly would be the case here since CenRfgwController inherits from CrestronGenericBaseDevice and registering the gateway would register all devices.

For the internal gateway, each infinet device still requires a register() call.

**To Reproduce**
1. Configure device as:
```
      {
        "name": "HR-150",
        "group": "remotes",
        "type": "hr150",
        "key": "hr150-1",
        "uid": 1,
        "properties": {
          "control": {
            "infinetId": "0x61"
          },
          "gatewayDeviceKey": "processor"
        }
      }
```

I set the debug level to 1 and couldn't see any of the buttonStateChange debug calls being triggered when pressing buttons.

**Expected behavior**
Hrxx0RemoteControl devices should have their own register() call if they are added to an internal gateway

**Screenshots**

**Additional context**

**Comment by jonavila** [comment]
Just wanted to add that in the mean time, I compiled from source and update the last part of the preactivation func so that it calls the Crestron's GenericBaseExtensions RegisterWithLogging method when the gatewayDeviceKey == "processor":

```
...
// right after getting the gateway
            Hr1x0WirelessRemoteBase remoteBase;
            switch (type)
            {
                case ("hr100"):
                    remoteBase = new Hr100(rfId, gateway);
                    break;
                case ("hr150"):
                    remoteBase = new Hr150(rfId, gateway);
                    break;
                case ("hr310"):
                    remoteBase = new Hr310(rfId, gateway);
                    break;
                default:
                    return null;
            }

            // register the device when using an internal RF gateway
            if (props.GatewayDeviceKey == "processor")
            {
                remoteBase.RegisterWithLogging(config.Key);
            }

            return remoteBase;

**Comment by TrevorPayne** [comment]
Strangely enough - that's almost exactly the fix I was fiddling with.  I don't have access to an MC3 to test against, unfortunately.

**Comment by jonavila** [comment]
> Strangely enough - that's almost exactly the fix I was fiddling with. I don't have access to an MC3 to test against, unfortunately.

Ha! happy to test for you in you put a fix in a branch

**Comment by TrevorPayne** [comment]
If you want to make a branch and commit this fix, please make sure you reference this issue in your commit;  "Resolves #262"

In this way we can link the commit to the issue explicitely and trigger a code review on what you have.

**Comment by andrew-welker** [comment]
Currently, that class inherits from EssentialsBridgeableDevice. Is there any reason that it couldn't be changed to inherit from CrestronGenericBridgeableBaseDevice? That class automatically includes registration as a PostActivationAction

**Comment by jonavila** [comment]
@andrew-welker That's what I was thinking of initially. I'd imagine that it is ok to register a device even if it's not necessary due to it being added to an external gateway that will be registered too.

**Comment by TrevorPayne** [comment]
I'm not sure that's going to necessarily work, because CrestronGenericBridgeableBaseDevice requires the device to be in the constructor.  I'm not sure I can do the post-activation device instantiation using the func<> pattern we are using now.
