### ISSUE TITLE
[FEATURE]-Remove Extraneous debugging on bridges

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#269]
**Is your feature request related to a problem? Please describe.**
Bridges by default debug their Actions when they are invoked, but they print the action to string, which ends up clogging the debug with useless information, as executing ToString() on an action doesn't tell you much.

**Describe the solution you'd like**
Remove this Debug altogether or at least have it debug something useful

**Additional context**
![image](https://user-images.githubusercontent.com/23391587/85141555-efc55b00-b214-11ea-9d2b-bccf03774724.png)

**Comment by TrevorPayne** [comment]
I disagree with the data being useless - it tells me that an action on a specific join has been triggered - quick head and shoulders view that my action is doing something.

I would support it being more selective in some way (like the new com method debugging options), but I don't think removing it altogether is warranted.

**Comment by ngenovese11** [comment]
Sure, I suppose I meant that the Action.ToString() text is mostly useless.

Nick Genovese
Developer
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>

PepperDash Mobile Control<http://www2.pepperdash.com/learn-about-mobile-control>™ - BYOD Crestron Control, no special app required

**Comment by ndorin** [comment]
The issue is that because the actions are lambdas there’s nothing more useful to print in the debug statement.

Sent from my iPhone

On Jun 19, 2020, at 8:32 AM, Nick Genovese <notifications@github.com> wrote:

﻿

Sure, I suppose I meant that the Action.ToString() text is mostly useless.

Nick Genovese
Developer
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>

PepperDash Mobile Control<http://www2.pepperdash.com/learn-about-mobile-control>™ - BYOD Crestron Control, no special app required

**Comment by ndorin** [comment]
I would support a changing to a more specific mechanism that only enables that debug output via a specific console command, but really that’s part of a much larger effort to add functionality to the Debug class in Core to enable specific debugging for any device.

Sent from my iPhone

On Jun 19, 2020, at 8:32 AM, Nick Genovese <notifications@github.com> wrote:

﻿

Sure, I suppose I meant that the Action.ToString() text is mostly useless.

Nick Genovese
Developer
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>

PepperDash Mobile Control<http://www2.pepperdash.com/learn-about-mobile-control>™ - BYOD Crestron Control, no special app required

**Comment by ngenovese11** [comment]
Could we at least move the debug level to 2 in the interim?

Nick Genovese
Developer
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>

PepperDash Mobile Control<http://www2.pepperdash.com/learn-about-mobile-control>™ - BYOD Crestron Control, no special app required

**Comment by ndorin** [comment]
Feel free to make a feature branch with that change. 👍

Sent from my iPhone

On Jun 19, 2020, at 9:19 AM, Nick Genovese <notifications@github.com> wrote:

﻿

Could we at least move the debug level to 2 in the interim?

Nick Genovese
Developer
PepperDash
www.pepperdash.com<http://www.pepperdash.com/>

PepperDash Mobile Control<http://www2.pepperdash.com/learn-about-mobile-control>™ - BYOD Crestron Control, no special app required
