### ISSUE TITLE
Add Output Disabled by HDCP feedback for DM outputs

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#28]
Add support to DmChassisController and DmChassisControllerBridge (with associated join map).

Should map on digital output joins 1201 - 1399.

**Comment by bitm0de** [comment]
> Should map on digital output joins 1201 - 1399.

Is this actuall **1401 - 1599** since `HdcpSupportCapability = 1200; //1201-1399`

**Comment by bitm0de** [comment]
Pull request #41 attempts to implement this functionality
