### ISSUE TITLE
[BUG]- Factory class for type "hdmd4x14ke" is missing

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#280]
**Describe the bug**
The `HdMdNxM4kEController` class is missing the matching Factory class to build an instance from a typename of `hdmd4x14ke`

**Expected behavior**
A typename of `hdmd4x14ke` should build an instance of `HdMdNxM4kEController`

**Comment by TrevorPayne** [comment]
Where are you seeing this?  I'm looking at it and I guess I don't see the problem - Here's the factory:

```
public static HdMdNxM4kEController GetController(string key, string name,
            string type, HdMdNxM4kEPropertiesConfig properties)
        {
            try
            {
                var ipid = properties.Control.IpIdInt;
                var address = properties.Control.TcpSshProperties.Address;

                type = type.ToLower();
                if (type == "hdmd4x14ke")
                {
                    Debug.Console(0, @"The 'hdmd4x14ke' device is not an Essentials Bridgeable device.  
                        If an essentials Bridgeable Device is required, use the 'hdmd4x14ke-bridgeable' type");
  
                    var chassis = new HdMd4x14kE(ipid, address, Global.ControlSystem);
                    return new HdMdNxM4kEController(key, name, chassis, properties);
                }
                return null;
            }
            catch (Exception e)
            {
                Debug.Console(0, "ERROR Creating device key {0}: \r{1}", key, e);
                return null;
            }
        }
```

**Comment by ndorin** [comment]
There needs to be a class that implements IDeviceFactory added to this file

**Comment by TrevorPayne** [comment]
Yeah - a little context - I was trying too hard to keep this class in a time capsule due to a client requirement from the legacy implementation of this device.  I completely glossed over it when converting all the classes to use the new joinmaps, and as such i didn't add a factory method here.  My bad, fixed!
