### ISSUE TITLE
[FEATURE]-Lutron QS expanded integration

### ISSUE THREAD

**Issue by ukypayne** [PepperDash/Essentials#293]
Current LutronQS integration was noted that "It only drives scenes at the moment, and, depending on the Lutron system design (how many NWK access points you have) it works with a single integration id at a time."

I would like and use expanded features including:

- [ ] Occupancy Sensors - likely exposing to SIMPLWindows

- [ ] Partition Sensor - exposing partition sensor (or really any CC reading) to SIMPLWindows

- [ ] Zone/Fixture/Preset Status

- [ ] Individual Fixture control - Ramping of fixture/zone

- [ ] Multiple NWK connections - ability to connect to multiple NWKs across a facility for centralized control

- [ ] Multiple simultaneous integration ID usage - ability to use multiple integration IDs at the same time for related control objects.

A redacted Lutron Integration Report can be provided to see an install example with a hundred+ separate integration IDs.

**Comment by jtalborough** [comment]
@ukypayne See public Lutron Quantum EPI https://github.com/PepperDash/epi-lighting-lutron_quantum. This does cover Partition Sensors and can be further expanded by the community. The Lutron device implementation in Essentials will be deprecated.
