### ISSUE TITLE
Plugin Infrastructure

### ISSUE THREAD

**Issue by bitm0de** [PepperDash/Essentials#30]
Currently what I can see is that plugins have to add themselves to the device config dictionary via a factory method that gets called from the parent side. It would be possible to avoid having to create this template each time if the plugin loading was automated all on the parent side. This can be achieved relatively cleanly with the use of custom attribute programming, and an Interface. One benefit of doing it this way is that it is also more type safe. The existing functionality just checks for a function name with specific binding flags to specify that the method needs to be public and marked as static, and the rest of the functionality relies on the exception handler.

With a slight code restructuring, all of that plugin functionality could be moved to the parent side and plugins would only require something like this:

```
[PluginDeviceEntryPoint("panasonicdisplay", "1.4.32")]
public class PanasonicDisplay : IPluginDeviceConfig
{
    public IKeyed BuildDevice(DeviceConfig dc)
    {
        throw new NotImplementedException();
    }
}
```

Use of an abstract class instead might also allow for extensibility without introducing breaking changes with additions to the plugin part. For the version that might be better suited as a Version type rather than a string as well for more suitable version comparisons. It would be left up to design decision, as to whether it should be in the attribute or kept as a property too.

Getting the custom attribute from the type and checking to see if it exists:
```
var entryPointAttribute = type.GetCustomAttributes(typeof(PluginEntryPointAttribute).GetCType(), false).FirstOrDefault() as PluginEntryPointAttribute;
if (entryPointAttribute != null) {

}
```

Checking for the interface:
`typeof(IPluginDeviceConfig).IsAssignableFrom(type)`

Then adding it to the dictionary:
(Note: `using Activator = Crestron.SimplSharp.Reflection.Activator;`)
```
var plugin = (IPluginDeviceConfig)Activator.CreateInstance(type);
PepperDash.Essentials.Core.DeviceFactory.AddFactoryForType(entryPointAttribute.UniqueKey, plugin.BuildDevice);
```

Although if you added the plugins directly to the dictionary, you would be able to do more with them via the interface (or abstract class).

**Comment by ndorin** [comment]
This sounds like something we could implement to make the defining things on the plugin side simpler (which is highly desired). 

At the time we hadn’t thought of a better way. This sounds like the approach we were going for. There are a number of plugins already using the existing method so if we can make this change non-breaking then I see no reason not to implement. Depot it makes it easier for newcomers to the framework to write plugins, which is our primary goal.

**Comment by bitm0de** [comment]
We could branch execution, and check for the type-safe way first, while still supporting the legacy method as a secondary check.
