### ISSUE TITLE
[BUG]-Slot after essentials doesn't wait for GoWithLoad() to complete

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#305]
**Describe the bug**
When Essentials is part of an app stack, it seems like it should be holding the next program from booting until the entire Plugin Loading sequence is complete.  Currently the next program boots immediately, and if it reads config itself will conflict with Essentials reading files.

**Additional context**
It seems to me like this is the intent; as there is a property on the SystemMonitor class for ProgramInitializationComplete set to true after the GoWithLoad() Method finishes.

**Comment by andrew-welker** [comment]
There are a couple of properties that need to be set. `SystemMonitor.ProgramInitialization.ProgramInitializationUnderUserControl` should be set to true, probably in the ControlSystem constructor. The actual complete signal should take place at the end of the `StartSystem` method, as the system would appear to hang if the system is set to not load on next boot.

**Comment by ndorin** [comment]
@ngenovese11 Can you elaborate more here on the issue.  There shouldn't be a problem with Essentials reading it's config file while other slots might be trying to read theirs.  The OS can handle multiple programs accessing the file system concurrently.

If, as @andrew-welker suggests, we need to set the other property to true, the `SystemMonitor.ProgramInitialization.ProgramInitializationComplete = true;` value should be set either if no config is found or after the config is read.

**Comment by ngenovese11** [comment]
Sure.  So what I was expecting to happen (and what I think is intended) is for all of the plugins to load and go through their activation phases before the next program slot begins to boot.  What actually happens is that the next program slot begins to boot almost immediately, and prior to Essentials even having a chance to read its own config file.  I think what is happening is not what it intended.

Nick Genovese
Developer
PepperDash
www.pepperdash.com
240.888.6090
PepperDash Mobile Control™ - BYOD Crestron Control, no special app required
________________________________
