### ISSUE TITLE
Create DynDm Virtual Device to capture existing DymDm functionality without affecting DmChassisController.  Needs own bridge method, join map and config

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#309]
New device should link to a chassis device via key and any specified DM endpoints (Tx/Rx) via keys defined in virtual device config.  It will need it's own bridge method, join map and config structure.

Once new device is tested, DmChassisController needs to have the bridge method updated to only affect the chassis itself and remove any interaction with endpoints.

**Comment by jtalborough** [comment]
DM will be moving to its own EPI
