### ISSUE TITLE
[FEATURE]-Create Standard VConf Bridge

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#326]
**Is your feature request related to a problem? Please describe.**
There's no mechanism to bridge VConf devices built in essentials across an eisc.

**Describe the solution you'd like**
This needs to start as a discussion point as for *what* needs to be bridged and how we can standardize between various VTC implementations

**Describe alternatives you've considered**
Currently, we bridge controls across to standard SIMPL VTC implementations in simpl - This becomes cumbersome in configurable codebases where we can have anywhere from 1 - 5 VTC units, and unnecessarily uses system resources for the vconf modules.

**Additional context**
This needs to start as an internal discussion, though external feedback and suggestions are welcome.

**Comment by jonnyarndt** [comment]
Would like to see the following integration bridged to SIMPL:
-Near end Quad Camera tracking on/off/toggle
-Local camera selection & control (PTZ, Preset selection and saving, feedback when preset saved)
-Far end camera selection & control (PTZ, preset selection)
-Near end presentation input selection and feedback
-Near end content/input selection and feedback
-Corporate directory polling and search, ability to call directly from items in list
-Local/favorites directory polling and search, ability to call directly from items in list, expand to allow users to add/remove contacts to the list
-Recent calls polling and call from items in list
-Volume control, mute, and feedback
-Ringer volume set and feedback
-Do-Not-Disturb state set and feedback
-Layout selection and feedback (auto, equal, overlay, prominent, and single)
-Direct serial input for keypad, keyboard, or override manual dial string from SIMPL
-Meeting info & OBTP (option to choose how soon to allow user to be able to start meeting prior to actual meeting)
-Call merging, multi-point calls up to 8 calls
-Call timer showing actual time in serial format for all current calls (updates every 3 seconds)
-Export people count and room occupancy data from endpoint into SIMPL
-Export network statistics & IP address info, endpoint URI, endpoint SIP address, endpoint phone number to SIMPL

**Comment by alex-johnson** [comment]
Looks like you captured just about everything. I also use PresenterTrack so control for that would be added to the list ideally.

**Comment by TrevorPayne** [comment]
A lot of that stuff doesn't fit "standard vconf" and are very specific for Cisco.

Please keep that in mind when making requests.

Trevor Payne, CTS, CCMP-Silver
Software Engineer
PepperDash
www.pepperdash.com
617.206.9807



PepperDash Mobile Control™ - BYOD Crestron Control, no special app required


On Jul 16, 2020 1:57 PM, Alex Johnson <notifications@github.com> wrote:

Looks like you captured just about everything. I also use PresenterTrack so control for that would be added to the list ideally.

**Comment by alex-johnson** [comment]
Wouldn't we still want those options and have an output to show supported/no supported? Or would we build a bridge for Cisco that inherits this bridge.

**Comment by TrevorPayne** [comment]
I would think that device-specific functions should have their own bridge.

Trevor Payne, CTS, CCMP-Silver
Software Engineer
PepperDash
www.pepperdash.com
617.206.9807



PepperDash Mobile Control™ - BYOD Crestron Control, no special app required


On Jul 16, 2020 2:08 PM, Alex Johnson <notifications@github.com> wrote:

Wouldn't we still want those options and have an output to show supported/not supported? Or would we build a bridge for Cisco that inherits this bridge.

**Comment by ndorin** [comment]
Thinks like PresenterTrack (though Cisco specific in naming) are widely found across other codecs and so we should include them (there’s already a generic interface) on the generic bridge but using a non Cisco specific name.

Sent from my iPhone

On Jul 16, 2020, at 1:12 PM, Trevor Payne <notifications@github.com> wrote:

﻿

I would think that device-specific functions should have their own bridge.

Trevor Payne, CTS, CCMP-Silver
Software Engineer
PepperDash
www.pepperdash.com
617.206.9807



PepperDash Mobile Control™ - BYOD Crestron Control, no special app required


On Jul 16, 2020 2:08 PM, Alex Johnson <notifications@github.com> wrote:

Wouldn't we still want those options and have an output to show supported/not supported? Or would we build a bridge for Cisco that inherits this bridge.

**Comment by andrew-welker** [comment]
Closing this for now. We can reopen/add a new issue at some future point
