### ISSUE TITLE
[FEATURE]-Add generic ReceiveQueue and TranmitQueue classes

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#398]
**Is your feature request related to a problem? Please describe.**
Receive and transmit queueing are tricky.  If we had a generic class for queuing messages of either type `string` or `byte[]` it would make life MUCH easier.

**Describe the solution you'd like**
Create classes like those created to fix the thread abort issue in the MC plugin to be used generically.

**Comment by ngenovese11** [comment]
Didn't know you could transfer issues, thanks!
