### ISSUE TITLE
[FEATURE]-Add OBVIOUS (ASCII Art maybe?) message to indicated when Essentials loads a local config file

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#399]
**Is your feature request related to a problem? Please describe.**
When Essentials loads a local config file (written by Essentials to the LocalConfig folder) it's not obvious to the developer that it's not using the config file in the root user folder for that program slot.  This can cause a fair amount of wasted time when making changes to the main config file but the program is using the local file and ignoring your new changes

**Describe the solution you'd like**
Add a very obvious message block in console to alert the developer

**Comment by ngenovese11** [comment]
I've made this same mistake many times.  Some documentation in the Wiki on how the Local Config works might also be helpful.  Thanks!
