### ISSUE TITLE
[FEATURE]- Update configuration for CameraVisca

### ISSUE THREAD

**Issue by jkdevito** [PepperDash/Essentials#413]
**Is your feature request related to a problem? Please describe.**
1. CameraPropertiesConfig does not include a configuration for Camera ID
2. No configuration for pan, tilt  speeds

**Describe the solution you'd like**
1. Extend CameraPropertiesConfig to create CameraViscaPropertiesConfig
1. Add support for Camera ID through configuration. 
1. Add configuration for pan, tilt slow/fast speeds and FastSpeedHoldTime.  If not defined a default value would be used.

**Comment by ndorin** [comment]
Is this for the Visca ID?

**Comment by jkdevito** [comment]
Correct, it appears all cameras are hard coded with a VISCA ID of 0x01.

**Comment by ndorin** [comment]
Ok, so if we add a config property for the ID and if no ID is specified in config (for backwards compatibility) we assume 0x01?  Will that work?

**Comment by jkdevito** [comment]
While updating the configuration object, can we add configuration for the pan, tilt, zoom speeds?

**Comment by ndorin** [comment]
@jkdevito do we want speeds for slow/fast?

**Comment by jkdevito** [comment]
In most cases we don't expose P/T/Z speed increment/decrement on the UI, however we are asked to change the speed to the customers liking, typically a set and forget value.  So, personally, I would  envision this as a numeric value (falling within the device limits).  If the value defined is outside of the limits a default value (middle of the range) would be used and a console message would be generated for the developer to notify them of the value was out of range.

**Comment by ndorin** [comment]
Right, set and forget config value, but most SIMPL modules have slow/fast config values that handle a faster speed when holding a camera direction button.  I'm going to allow for configurable properties for two speeds

**Comment by ndorin** [comment]
Extends CameraPropertiesConfig to include the following:

``` CSharp
 public class CameraViscaPropertiesConfig : CameraPropertiesConfig
    {
        /// <summary>
        /// Control ID of the camera (1-7)
        /// </summary>
        [JsonProperty("id")]
        public uint Id { get; set; }

        /// <summary>
        /// Slow Pan speed (0-18)
        /// </summary>
        [JsonProperty("panSpeedSlow")]
        public uint PanSpeedSlow { get; set; }

        /// <summary>
        /// Fast Pan speed (0-18)
        /// </summary>
        [JsonProperty("panSpeedFast")]
        public uint PanSpeedFast { get; set; }

        /// <summary>
        /// Slow tilt speed (0-18)
        /// </summary>
        [JsonProperty("tiltSpeedSlow")] 
        public uint TiltSpeedSlow { get; set; }

        /// <summary>
        /// Fast tilt speed (0-18)
        /// </summary>
        [JsonProperty("tiltSpeedFast")]
        public uint TiltSpeedFast { get; set; }

        /// <summary>
        /// Time a button must be held before fast speed is engaged (Milliseconds)
        /// </summary>
        [JsonProperty("fastSpeedHoldTimeMs")]
        public uint FastSpeedHoldTimeMs { get; set; }

    }
```
