### ISSUE TITLE
[FEATURE]-Remove all device RX/TX debug statements now that IStreamDebugging exists

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#417]
**Is your feature request related to a problem? Please describe.**
Some device classes print RX/TX data from the device at debug level 1 or 2.  This clutters up console debugging significatly.

**Describe the solution you'd like**
Remove all RX/TX debug statements in all devices that implement IBasicCommunication

**Comment by jonnyarndt** [comment]
@ndorin or @andrew-welker, please provide additional verbose directions. Would it be safe to assume that all classes implementing IBasicCommunication that include 'Debug.Console' (levels 1 & 2) are to be replaced with IStreamDebugging (keeping the debugging in-place but with a new mechanism for when to show them)? Or, should the 'Debug.Console' lines simply be deleted with nothing replacing them?

**Comment by ndorin** [comment]
@jonnyarndt All device classes that currently have debug statements to print data received or transmitted via an IBasicCommunication need to have those statements removed.

We've added the IBasicCommunicationWithStreamDebugging interface and implmented it on the necessary classes (ComPortController/GenericTcpIpClient/GenericSshClient/GenericUdpClient/etc.) except `CecPortController` (see #642) throughout PepperDash.Core and Essentials.  This gives the ability to enable/disable RX/TX messages from console commands regardless of the debug level and is much more useful and preferable.  

The best way to accomplish this would be to search through the Essentials code for "RX:" and "TX:" and their variants to find any debug statements.  If those statements are in a device class that talks to a 3rd party device, they should be deleted.

**Comment by jonnyarndt** [comment]
@ndorin, when I compile the solution I see a bunch of missing DLL's. Could you forward me a copy of what the 'packages.config' file should contain? Nuget seems to only be pulling down the DLL for PepperDash Core but nothing else.

**Comment by ndorin** [comment]
@jonnyarndt what specific .dlls is the compiler complaining are missing?  The only dependency .dlls that don't get build during the compile process of Essentials are Pepperdash.Core and the Crestron .dlls from the databases.  The only .dll that nuget should pull down in PepperDash.Core
