### ISSUE TITLE
[FEATURE]-Add mechanism for reporting device information

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#426]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to get device-specific information, such as mac address, serial numbers, or firmware from devices out of essentials and across a bridge.

**Describe the solution you'd like**
There should be an interface that defines reporting of that data that can be implemented on a per-device basis to pass pertinent device data across.  Each device need not report its data on its own bridge, but perhaps create a class that grabs specific devices by key from the device manager and reports data as requested.  This *should* have minimal impact on each individual class and would allow developers to implement the interface on devices on an as-needed basis.  This solution would also allow for any fusion implementation utilizing essentials to grab device information with little to no additional effort by leaning on the interface implementation in asset reporting.

**Describe alternatives you've considered**
In the past, I've opened individual sockets to devices to request this data, or removed them from essentials altogether.

**Additional context**
This data is important for asset tracking in fusion.

**Comment by TrevorPayne** [comment]
Desired Information:

Hostname,
IP Address,
Netmask, (Less Important)
DNS, (Less Important)
Gateway, (Less Important)
MAC,
Serial,
Firmware

**Comment by TrevorPayne** [comment]
DM Receivers
DM Tx
DM Chassis
DGE
Airmedia

Need to add this interface to PDU Plugins, Mic Plugins, Tesira Plugin

**Comment by ndorin** [comment]
Appears to be complete via #484
