### ISSUE TITLE
[FEATURE]-Create IDspPreset interface

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#457]
**Is your feature request related to a problem? Please describe.**
We need to create an interface for DSPs to implement for preset recall so that essentials can recall presets for those devices

**Describe the solution you'd like**
Interface should have methods for recalling preset by Name, but Index, by Id - to cover all the options.

**Comment by ndorin** [comment]
This interface should not contain any properties or methods specific to a particular brand of DSPs requirements. The interface should assume a generic collection of presets and use a generic selector. The implementation on a particular class should deal with specifics.
