### ISSUE TITLE
[FEATURE]-Add Interface for IRouting OnRoute Events

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#467]
**Is your feature request related to a problem? Please describe.**
There isn't an easy device or interface to cast an IRouting device to in order to get route feedbacks.  As of now, you would have to cast to each device type, and even then you would have to use the existing feedback classes which could leave a bit to be desired.

**Describe the solution you'd like**
Create an interface with an event that describes a route (input, output, sigtype) that fires whenever a route changes on the device.

**Additional context**
This is fairly essential (heh) for BusinessLogic plugins that want to manage switching externally from an Essentials Room.

**Comment by ngenovese11** [comment]
Could subscribe to the InUse feedback on the Routing Outputs?

**Comment by andrew-welker** [comment]
`RoutingOutputPort` doesn't implement an interface, and the `InUse` feedback isn't triggered when a route changes from a non-Essentials stimulus, like someone using the front panel.

**Comment by ngenovese11** [comment]
Correct, someone would have to code it.  The solution that @TrevorPayne came up with seems easier.
