### ISSUE TITLE
[FEATURE]-incorporate GenericHttpClient into the ComFactory.CreateCommForDevice method

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#47]
**Is your feature request related to a problem? Please describe.**
I would like to be able to receive a GenericHttpClient from the ComFactory

**Describe the solution you'd like**
Add Http to the eControlMethod enum and return a GenericHttpClient from the ComFactory.CreateCommForDevice method

**Describe alternatives you've considered**
Instantiating the GenericHttpClient myself

**Additional context**

**Comment by jtalborough** [comment]
+1

**Comment by andrew-welker** [comment]
I'm going to close this issue for now. We've got an issue on the PepperDash Core board to create a new interface for HTTP/S Communications, as that style of communications doesn't fit the standard stream model that `IBasicCommunications` uses.
