### ISSUE TITLE
[FEATURE]-Add the following parameters to the SystemMonitorController class and the Eisc Bridge

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#50]
**Describe the solution you'd like**
Should gather and report on the following 
"SystemUptime" : 			
"FirmwareVersion" :	 		
"FirmwareDate" : 			
"Hostname" : 				
"SerialNumber" : 			
"Model" : 					
"IPAddressMain" : 			
"IPAddressControlSubnet" : 	
"DefaultRouter" : 			
"Domain" : 					
"DnsServers" : 				
"MacAddressMain" : 			
"MacAddressControlSubnet" : 
"SubnetMaskMain" : 			
"SubnetMaskControlSubnet" :

**Comment by minesguy82** [comment]
@jtalborough How often should uptime be updated? I'm thinking we'll set a default and allow it to be overridden by config, with a minimum of something like 1 minute. Thoughts?

**Comment by minesguy82** [comment]
@jtalborough  What serial number format should be returned? It's not so easy to translate between the hex value returned by `VER` and the serial number that's on the sticker on the processor any more.

**Comment by jtalborough** [comment]
@minesguy82 
> @jtalborough How often should uptime be updated? I'm thinking we'll set a default and allow it to be overridden by config, with a minimum of something like 1 minute. Thoughts?

I think 5min intervals, IMHO. This is what DynFusion currently does. 

> @jtalborough What serial number format should be returned? It's not so easy to translate between the hex value returned by `VER` and the serial number that's on the sticker on the processor any more.

Im not sure on this one. It's a field in our standard Fusion implementation. I have been using the Hex value and this is what DynFusion is sending i believe. It's worth mentioning on the next call.

**Comment by andrew-welker** [comment]
Closed as this was released already.
