### ISSUE TITLE
[BUG]-Non-Feedback bridge values don't repropegate when EISC comes online

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#55]
**Describe the bug**
Values bridged to SIMPL not coming from Feedback objects that are just set directly to the StringInput/BooleanInput/UshortInput collection on the Trilist don't repropegate if the far end EISC goes offline and comes back offline

Example:
``` csharp
trilist.UShortInput[joinMap.HdcpSupportCapability].UShortValue = (ushort)tx.HdcpSupportCapability;
```

**Expected behavior**
What needs to happen is that we should subscribe to the trilist.OnlineStatusChange event in the affected bridges and write a lambda that resends the affected values went the EISC is online.

Proposed fix for example:

``` csharp
// Set the value initially
            trilist.UShortInput[joinMap.HdcpSupportCapability].UShortValue = (ushort)tx.HdcpSupportCapability;

// Adds event handler lambda to set the value when the EISC comes back online
            trilist.OnlineStatusChange += new Crestron.SimplSharpPro.OnlineStatusChangeEventHandler((d, args) =>
            {
                if (args.DeviceOnLine)
                {
                    trilist.UShortInput[joinMap.HdcpSupportCapability].UShortValue = (ushort)tx.HdcpSupportCapability;
                }
            });
```

**Additional context**
Affects bridge extension methods where values are sent from Essentials NOT using the LinkInputSig extension method

**Comment by andrew-welker** [comment]
I'm assuming that this still needs to be done or at least verified in internal Essentials Devices, correct?
