### ISSUE TITLE
[FEATURE]-GenericQueue upgrades

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#560]
**Is your feature request related to a problem? Please describe.**
* There is no way to set the thread priority level for the worker thread in GenericQueue.
* ProcessQueue calls Debug.ConsoleWithLog which is not the correct method to log to the error log.  It should instead use the Debug.Console() overload that takes a Debug.ErrorLogLevel parameter

**Describe the solution you'd like**
* We should add a constructor overload that takes in eThreadPriority to allow the priority to be set for a GenericQueue instance
* Update all instances of Debug.ConsoleWithLog to correct Debug.Console overload

**Comment by ngenovese11** [comment]
While we're making this change we should increase the size of the queue.  It defaults to "5" and its not clear to me whether this expands or not.  I've never actually ran into a problem, but my guess is that the "Add" method for the queue blocks until there are open slots in the queue.

**Comment by ngenovese11** [comment]
1.7.3 throws exception in queue:

```System.ArgumentException:  Invalid priority .
   at Crestron.SimplSharpPro.CrestronThread.Thread.set_Priority(eThreadPriority value)
   at PepperDash_Essentials_Core.Queues.GenericQueue..ctor(String key, eThreadPriority priority)
   at PepperDash_Essentials_Core.Queues.GenericQueue..ctor(String key)
   at Epi.Display.Lg.LgDisplayController..ctor(String key, String name, LgDisplayPropertiesConfig config, IBasicCommunication comms)
   at Epi.Display.Lg.LgDisplayControllerFactory.BuildDevice(DeviceConfig dc)
   at PepperDash.Essentials.Core.DeviceFactory.GetDevice(DeviceConfig dc)
   at PepperDash.Essentials.ControlSystem.LoadDevices()
   at PepperDash.Essentials.ControlSystem.Load()
   at PepperDash.Essentials.ControlSystem.GoWithLoad()
   at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
   at Crestron.SimplSharp.CTimer.a(Object A_0)
   at System.Threading.Timer.ring()
```

**Comment by andrew-welker** [comment]
> 1.7.3 throws exception in queue:
> 
> ```
>    at Crestron.SimplSharpPro.CrestronThread.Thread.set_Priority(eThreadPriority value)
>    at PepperDash_Essentials_Core.Queues.GenericQueue..ctor(String key, eThreadPriority priority)
>    at PepperDash_Essentials_Core.Queues.GenericQueue..ctor(String key)
>    at Epi.Display.Lg.LgDisplayController..ctor(String key, String name, LgDisplayPropertiesConfig config, IBasicCommunication comms)
>    at Epi.Display.Lg.LgDisplayControllerFactory.BuildDevice(DeviceConfig dc)
>    at PepperDash.Essentials.Core.DeviceFactory.GetDevice(DeviceConfig dc)
>    at PepperDash.Essentials.ControlSystem.LoadDevices()
>    at PepperDash.Essentials.ControlSystem.Load()
>    at PepperDash.Essentials.ControlSystem.GoWithLoad()
>    at PepperDash.Essentials.ControlSystem.StartSystem(Object obj)
>    at Crestron.SimplSharp.CTimer.a(Object A_0)
>    at System.Threading.Timer.ring()
> ```

What's the actual exception?

**Comment by ngenovese11** [comment]
System.ArgumentException:  Invalid priority .

sorry I reformatted the exception in the comment above

**Comment by andrew-welker** [comment]
Got it. I think I know why. I'll fix it.

**Comment by ndorin** [comment]
crap.  Apparently it doesn't like the eThreadPriority.NotSet value.  That doesn't make a lot of sense....

**Comment by ngenovese11** [comment]
yeah from the comments on "NotSet" maybe it doesn't like it because the thread is already running

**Comment by andrew-welker** [comment]
What should be the default priority for something like this? I'd think medium...definitely not uber...

**Comment by ngenovese11** [comment]
I'd say medium too...
