### ISSUE TITLE
[FEATURE]-SetTopBox-Bridge-Exposure

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#60]
**Is your feature request related to a problem? Please describe.**
There is no way to expose an IR set top box to simpl from essentials

**Describe the solution you'd like**
A bridge needs to be created to expose settopbox to the eisc for simpl

**Describe alternatives you've considered**
Considered creating a plugin, but seems excessive when it should be a part of essentials

**Comment by minesguy82** [comment]
Closed by pr #64
