### ISSUE TITLE
[FEATURE]-GenericQueue Enhancements

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#600]
**Is your feature request related to a problem? Please describe.**
There is no way to check the count of the internal CrestronQueue inside the GenericQueue Class

**Describe the solution you'd like**
Add a public property with a getter that returns the count of the internal CrestronQueue.  Also add additional constructors to allow setting the size of the internal CrestronQueue.

**Comment by andrew-welker** [comment]
We should also add a property to get the capacity of the queue, along with a constructor to allow for setting the capacity if a capacity something other than the default of 25 is desired.

**Comment by ndorin** [comment]
I think we both mean the same thing in terms of the additional constructor.  You're basically just suggesting an additional property which reports the internal queue's capacity (set when constructed) in addition to the queue's current size/count? Correct @andrew-welker ?

**Comment by andrew-welker** [comment]
Yep...I didn't read the initial issue fully, doh.
