### ISSUE TITLE
[FEATURE]-Make the CountdownTimer class a bridgeable device

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#641]
**Is your feature request related to a problem? Please describe.**
The countdown timer is useful, and would be helpful as a bridgeable device to simpl.

**Describe the solution you'd like**
Make the countdown timer a Bridgeable Device

**Describe alternatives you've considered**
I've created a countdown timer plugin, but ultimately its just a redundant wrapper.  I'd like to deprecate it.

**Comment by andrew-welker** [comment]
We'll also have to add a factory to allow for creation of the device in Essentials.

**Comment by ngenovese11** [comment]
class = PepperDash.Essentials.Core.SecondsCountdownTimer
file = CountdownTimer.ds
sln folder = Core/Timers

**Comment by jtalborough** [comment]
i belive this is complete
