### ISSUE TITLE
[FEATURE]-Implement IBasicCommunicationWithStreamDebugging on CecPortController

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#642]
**Is your feature request related to a problem? Please describe.**
`CecPortController` does not currently implement `IBasicCommunicationWithStreamDebugging`

**Describe the solution you'd like**
Implement `IBasicCommunicationWithStreamDebugging`

**Additional context**
Use `ComPortController` as an example for implementation details

**Comment by ediablo80** [comment]
Updates CecPortController class to implement IBasicCommunicationWithStreamDebugging basd on training video (compared with ComPortController as example of a class with this already implemented)
