### ISSUE TITLE
[FEATURE]-Secrets Manager

### ISSUE THREAD

**Issue by andrew-welker** [PepperDash/Essentials#685]
**Is your feature request related to a problem? Please describe.**
In order to manage passwords for devices like video conference codecs, we'd like to implement a secrets manager. To start out, this will be relatively simple, consisting of an interface called `ISecretProvider`, an interface called `ISecret` and a `SecretsManager`. This would allow us to add other providers to interact with corporate secrets managers via plugins at a later date. 

# ISecretProvider
The `ISecretProvider` interface should inherit from `IKeyed`, and look something like below:
```cs
public interface ISecretProvider : IKeyed
{
     SetSecret(string key, object value);

     ISecret GetSecret(string key);
}
```

## ISecret
The `ISecret` interface allows for normalization of data between various providers.
```cs
public interface ISecret
{
    IParent provider {get;}
    string key {get;}
    object value {get;}
}
```
# Secrets Manager
The Secrets Manager in Essentials should contain a collection of `ISecretProvider` objects, allowing for multiple providers if necessary. There will be a default provider that uses the CrestronStore on a processor to store data. This default provider will be created automatically by the Secrets Manager. It might be possible to store whole objects, if they're serialized to JSON, but that may or may not be useful.

The Secrets Manager should declare console commands for CRUD operations on secrets. The secrets will NOT be encrypted for now.

# Using secrets in a configuration
The proposed method for using secrets is to have the property that needs them replaced with a config structure that specifies the key that's needed. Something like:
```json
{
        "id": "d1f5d2e7-01ea-4153-9299-16c2112ce168",
        "name": "Video Codec",
        "key": "videoCodec",
        "type": "ciscoSpark",
        "uid": 8,
        "group": "videoCodec",
        "properties": {
          "control": {
            "method": "ssh",
            "tcpSshProperties": {
              "port": 22,
              "address": "test.domain.com",
              "username": "controlsystem",
              "password": {
                "secret": {
                  "provider": "default", 
                  "key": "vcPassword"
                }
              },
              "autoReconnect": true,
              "autoReconnectIntervalMs": 5000,
              "bufferSize": 32768
            }
          }
}
```

When devices are created by the factory, any values that have the `secret` object as it's value will be replaced by retrieving the value from the `SecretsManager`, based on the provider and key value in the secret object. Once that is complete, the `DeviceConfig` with the replaced value will be used in the factory method for the device.

Planned future enhancements also include enabling OAuth Device flow authentication.

**Comment by TrevorPayne** [comment]
Why not encrypt the secrets for now?  I have a working workflow for on the fly encrypting and decrypting that I have working in 3 series.  Granted, it's using "not the greatest" encryption algorithms, but if we're just creating a secrets file somewhere, it's no different then leaving the passwords in plaintext in that config.

At least have encrypt/decrypt with the system key or something...or is it just because we want to start with an MVP?

**Comment by srayancha** [comment]
The issue with encryption is the maintenance of the encryption key to be used. We could do this in the future if we could find a way to use a non-extractable key.  Since credentials are usually required to access the processor, the data stored on the processor can be considered "secured" as opposed to a config with secrets in them that will usually be backed up externally.

**Comment by TrevorPayne** [comment]
@andrew-welker I'm concerned with this portion now..

"Once that is complete, the DeviceConfig with the replaced value will be used in the factory method for the device."

I'm about to test this, but won't this mean that once the secrets are read in, a localConfig write would overwrite the `secrets` object in the config with the actual value?

**Comment by andrew-welker** [comment]
Yes. There are some ways to keep that from happening though. Probably the easiest is to add a constructor to the `DeviceConfig` class that takes in a `DeviceConfig` as a parameter, along with parameterless one. The constructor that takes a `DeviceConfig` would set all the values to the same as it's incoming `DeviceConfig`, essentially creating a copy of the DeviceConfig. We'd probably have to use the `JToken.FromObject` to get a new JToken reference. This copy is then what would be fed into the DeviceFactory, leaving the copy in the config alone.

**Comment by TrevorPayne** [comment]
THen you have to pepper this new DeviceConfig(DeviceConfig dc) throughout essentials to make sure this works, right?  Or am I missing something simple?

**Comment by andrew-welker** [comment]
Only when you have to replace a secret...

**Comment by andrew-welker** [comment]
Which is why we add a default constructor.

**Comment by TrevorPayne** [comment]
Something Like this then?

```CSharp
public class DeviceConfig
    {
        [JsonProperty("key")]
        public string Key { get; set; }

        [JsonProperty("uid")]
        public int Uid { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("group")]
        public string Group { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        [JsonConverter(typeof(DevicePropertiesConverter))]
        public JToken Properties { get; set; }

        public DeviceConfig(DeviceConfig dc)
        {
            Key = dc.Key;
            Uid = dc.Uid;
            Name = dc.Name;
            Group = dc.Group;
            Type = dc.Group;
            Properties = JToken.FromObject(dc.Properties);
        }
    }```

**Comment by andrew-welker** [comment]
Add a default constructor, `public Device config() {}` and you've got it.

**Comment by TrevorPayne** [comment]
Looks like the standard CrestronDataStoreStatic no longer works on 4-series - it refuses to actually save values.

My code works fine on 3-series.

@srayancha There's a secure crestron data store in the latest include4.dat which is supported by 3 series as well with the latest firmware.  Granted, I could just change it to the secure storage for 4-series only - but that brings in the question of "what key do I use"....I think it warrants further discussion.

**Comment by srayancha** [comment]
I think the Secure Data Store is ok to use. We just need to require the latest firmware then, correct?

**Comment by TrevorPayne** [comment]
Correct

**Comment by TrevorPayne** [comment]
We may want to add a property to the secret that defines the data type of the secret, since the CrestronSecureDataStore sets everything as a byte array - we need to know what to convert it back to?

```Javascript
"secret": 
{
    "provider": "default", 
    "key": "vcPassword",
    "dataType" : "string"
}

**Comment by srayancha** [comment]
Wouldn't we just assume it's text in and out?

**Comment by TrevorPayne** [comment]
We can - sure.
