### ISSUE TITLE
[BUG]-DevJson method calls that have enum parameters cannot be called

### ISSUE THREAD

**Issue by TrevorPayne** [PepperDash/Essentials#715]
**Describe the bug**
Attempting to use DevJson to call a method that has enum parameters fails with a cast exception

**To Reproduce**
1. Create a device that implements an interface containing the `ExecuteSwitch` method
2. attempt to use DevJson to call Execute switch.
3. Using string for the enum, or the backer int fails.

**Expected behavior**
at least for things that have simple type representations, DevJson should make an attempt to cast or convert when possible.

**Comment by andrew-welker** [comment]
Is there an exception that happens when you attempt to use a string or an int for the enum value? DevJson does already attempt to convert the params to the correct types for the method.

**Comment by TrevorPayne** [comment]
```PRO3>devjson {"deviceKey" : "switcher", "methodName" : "ExecuteSwitch", "params" : [1, 1, "Video"]}
Unable to call method with name ExecuteSwitch. Invalid cast from 'System.String' to 'PepperDash.Essentials.Core.eRoutingSignalType'.```

```PRO3>devjson {"deviceKey" : "switcher", "methodName" : "ExecuteSwitch", "params" : [1, 1, 1]}
Unable to call method with name ExecuteSwitch. Invalid cast from 'System.Int64' to 'PepperDash.Essentials.Core.eRoutingSignalType'.```

**Comment by andrew-welker** [comment]
What device are you attempting this on? What does the response to the `devmethods` command show for all overloads of `ExecuteSwitch`?

Also, I'll look into the casting thing. One option @ndorin and I have talked about is adding an explicit type option to the command (or creating another command that takes that information). That could potentially solve this issue, along with allowing you to select the correct overload of the value.

**Comment by TrevorPayne** [comment]
```JS
{
    "Name": "ExecuteSwitch",
    "Params": [
      {
        "Name": "input",
        "Type": "UInt32"
      },
      {
        "Name": "output",
        "Type": "UInt32"
      },
      {
        "Name": "signalType",
        "Type": "eRoutingSignalType"
      }
    ]
  }
```

Direct report from DevJson for this device.

**Comment by andrew-welker** [comment]
Build 1.9.1-hotfix-1391 should allow for methods with enum parameters to be called as string values. Int values will still fail. Flag values, like `eRoutingSignalType`, can be called by separating the values with a comma, e.g. `audio, video`. There is a larger discussion to still be had about improving this method. It will still fail if types aren't simple value types like a string, integer, or now enum.
