### ISSUE TITLE
[Documentation]-List of included Device Types and associated type Keys

### ISSUE THREAD

**Issue by andrew-welker** [PepperDash/Essentials#73]
We need to document what types are included in Essentials along with the types that go in the `type` property in a configuration file.

**Comment by derek555** [comment]
I think it would be useful if this were a part of the Supported-Devices wiki page: (https://github.com/PepperDash/Essentials/wiki/Supported-Devices). Maybe the ordered list can be turned into a multi-column table with the first column being the common name and the second column being the specific device-type named required in the JSON configuration file. Maybe in the future a hot-link can be setup between that device-type and a page that details the methods supported and example configuration for the device.

**Comment by ndorin** [comment]
> I think it would be useful if this were a part of the Supported-Devices wiki page: (https://github.com/PepperDash/Essentials/wiki/Supported-Devices). Maybe the ordered list can be turned into a multi-column table with the first column being the common name and the second column being the specific device-type named required in the JSON configuration file. Maybe in the future a hot-link can be setup between that device-type and a page that details the methods supported and example configuration for the device.

We're going to go a couple steps beyond this actually and we're in the process of building in a mechanism for Essentials to self report the types it supports via console commands at runtime.  This is targeted for the 1.5.0 milestone release and should be available in the next week or so.  Initially this will report the correct type value for each supported device as well as a description for context.  We may expand this in the future to also add an option to get the details for a specific device and return a snippet of JSON config needed to generate an instance of the device.

**Comment by ndorin** [comment]
Relates to #106

**Comment by derek555** [comment]
Awesome! Kind of bit me again last night when I had to search the source code for the correct type name for the NEC display type. 👍
