### ISSUE TITLE
[FEATURE]-Feedbacks (bool, int, string) need the ability to retrigger on a FireUpdate regardless of current value 

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#757]
Currently the feedback will only trigger when the value is different than the current Feedback value. Certain applications require the same value be sent multiple times. 

PepperDash.Essentials.Core.BoolFeedback 
line 75
```
if (newValue != _BoolValue)
            {
                _BoolValue = newValue;
                LinkedInputSigs.ForEach(s => UpdateSig(s));
                LinkedComplementInputSigs.ForEach(s => UpdateComplementSig(s));
                OnOutputChange(newValue);
            }
```

**Comment by ndorin** [comment]
@jtalborough  Can you give a description of the applications for this change that require the same value to be sent multiple times?  

I'm concerned that this method will have much more widespread effects that may be required to solve the core issue that they're trying to address.  This would be a very hard mechanism to make configurable and would effectively result in code that causes the `OnOutputChange` event to be fired unnecessarily, when the output value has not in fact changed.  

I'm wondering if there might be an alternative mechanism to address the core issue that might more narrowly address it without the potential unintended side effects.

Can you help us understand this better?

**Comment by ndorin** [comment]
Superceded by #759
