### ISSUE TITLE
[FEATURE]-Add a static bool property to the DeviceManager class indicating that all devices have been activated

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#760]
**Is your feature request related to a problem? Please describe.**
This feature would add a bit more functionality to the AllDevicesActivated event in that you would not have to subscribe directly/maintain the state unless you explicitly needed to.  There are certain methods I might return out of if not all devices are activated and it would be easy to do a check against the global bool as opposed to subscribing/maintaining the state myself.

**Describe the solution you'd like**
static bool property on the DeviceManager class AllDevicesAreActivated

**Describe alternatives you've considered**
subscribing/maintaining the state internally to the plugin when needed

**Comment by andrew-welker** [comment]
I'm not sure this is necessary. There was a new virtual method, `Initialize`, added to the `Device` class in PD Core 1.0.48, and Essentials 1.10.0 subscribes to the `AllDevicesActivated` and calls the `Initialize` method. Plugins can then override the `Initialize` method and do things that shouldn't be done in the activation phase there. If the plugin needs to track the activation state, it can do it that way, or it can just kick off the process in the `Initialize` method and go from there.

See #755 and the associated PR #756
