### ISSUE TITLE
[FEATURE]-Samsung MDC Display provide current input feedback

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#778]
**Is your feature request related to a problem? Please describe.**
From what I can tell, the Samsung MDC device only provides current input feedback reflecting power state.  Could someone review and make sure I'm not missing something?  I'm utilizing this device in a project and need to show current input selected.

**Describe the solution you'd like**
Current input reflected on an analog input to the bridge.

**Comment by andrew-welker** [comment]
We have a Samsung plugin that has been more maintained than the Essentials class. I'd use that plugin instead of the built-in functionality.

**Comment by TrevorPayne** [comment]
I'm with @andrew-welker on this one - I feel like we should probably close this issue - but it does bring up the question of why we still maintain the samsung device within essentials when there's a more fully-functional plugin.

**Comment by andrew-welker** [comment]
I think it is marked as obsolete...and if it's not, it should be with a note to use the EPI. Most of the display classes that are in Essentials proper should be marked that way. We'll remove them in the next major version release.

**Comment by ndorin** [comment]
Is the Samsung plugin public?

Sent from my iPhone

On Mar 15, 2022, at 10:59 PM, Andrew Welker ***@***.***> wrote:

﻿

I think it is marked as obsolete...and if it's not, it should be with a note to use the EPI. Most of the display classes that are in Essentials proper should be marked that way. We'll remove them in the next major version release.

**Comment by TrevorPayne** [comment]
> Is the Samsung plugin public?


Yes - the samsung plugin is public and is feature complete and (now) essentials compliant.

I would recommend closing this issue @jtalborough @ndorin
