### ISSUE TITLE
[BUG]-DM endpoints for non 4K DMPS3 units not registering properly

### ISSUE THREAD

**Issue by alex-johnson** [PepperDash/Essentials#824]
DMPS3-300-C and DMPS3-200-C are different from the DMPS3-4K type units and required the IP ID for DM endpoints. When trying to add a DM endpoint to a DMPS3-200-C, there is an exception that the wrong registration method was used.

**Comment by alex-johnson** [comment]
Resolved by  #839

**Comment by andrew-welker** [comment]
We're still working on making some changes to this. We'll close this issue once it makes it into a full release.

**Comment by ndorin** [comment]
@alex-johnson  #843 makes the necessary changes to deal with all endpoint registration issues.  Merge latest `development` into your fork for updates.
