### ISSUE TITLE
[BUG]-InitializeSystem() needs to wait for DMPS endpoints to register at startup

### ISSUE THREAD

**Issue by alex-johnson** [PepperDash/Essentials#826]
DMPS HDBaseT endpoints must be registered before InitializeSystem() occurs. However, there is currently nothing stopping InitializeSystem() from happening immediately at boot.

Can we delay InitializeSystem() until all devices are registered?

When attempting to register the endpoint after InitializeSystem(), the endpoint will show up in the iptable but never come online.

**Comment by alex-johnson** [comment]
Resolved by #839

**Comment by andrew-welker** [comment]
We're still working on making some changes to this. We'll close this issue once it makes it into a full release.

**Comment by ndorin** [comment]
@alex-johnson this is resolved in latest `development` branch.
