### ISSUE TITLE
[FEATURE]-ZoomRooms bridge needs to be updated to support existing functionality

### ISSUE THREAD

**Issue by cdenig** [PepperDash/Essentials#868]
**Is your feature request related to a problem? Please describe.**
User is unable to enter a password when a Meeting requires a password.

**Describe the solution you'd like**
Let a user enter a password either before or after connecting to a Meeting (incoming or outgoing).  Support re-try password entry.
Provide Digital "toSIMPL" when a Meeting is requiring a Password is true. (clear on false or successful/abandoned connection)
Provide Digital "toSIMPL" when WrongAndRetry is true.
Provide a Serial "fromSIMPL" string for password text entry.
Provide a Digital "fromSIMPL" to re-send Dial command with entered password (outoging) or send command required by incoming call

**Describe alternatives you've considered**
Might be required that ZoomRoom keeps direct control over UI popup page visibility rather than more raw feedback described above.

**Additional context**
https://marketplace.zoom.us/docs/guides/zoom-rooms/zoom-rooms-cli/zEvents#zevent-meetingneedspassword
https://marketplace.zoom.us/docs/guides/zoom-rooms/zoom-rooms-cli/zEvents#zevent-incomingcallindication

@jkdevito

**Comment by andrew-welker** [comment]
The ZoomRoom class supports this and it is already supported for stand-alone Essentials rooms. The ZoomRoom join map just needs the functionality added  to map the joins over to SIMPL.

**Comment by jkdevito** [comment]
Updated the issue title to accurately reflect the issue beyond just the password functionality.

The following features will require LinkToApi updates to bridge into SIMPL:
1. Show password prompt
2. Password incorrect feedback
3. Need to wait for host feedback
4. Start meeting now trigger
5. Start share only meeting trigger
6. Share only meeting feedback
7. Is host feedback
8. Password entry input
9. Password prompt message
10. Meeting ID feedback
11. Meeting Host feedback
12. Meeting password feedback
