### ISSUE TITLE
[FEATURE]-Split up volume/mute interfaces

### ISSUE THREAD

**Issue by ngenovese11** [PepperDash/Essentials#915]
**Is your feature request related to a problem? Please describe.**
Currently IBasicVolumeControls and IVasicBolumeWithFeedback assume that you require both volume and mute controls.  These should be split for better composition, as there is no guarantee a device that supports volume also supports mute.  If they are properly broken up and the existing interfaces derive from them, then backwards compatibility will be maintained. 

**Describe the solution you'd like**
IHasVolumeControl, IHasVolumeControlWithFeedback, IHasMuteControl, IHasMuteControlWithFeedback
IBasicVolumeControls -> IHasVolumeControl, IHasMuteControl
IBasicVolumeWithFeedback -> IBasicVolumeControls, IHasVolumeControlWithFeedback, IHasMuteControlWithFeedback

**Comment by TrevorPayne** [comment]
I like the increased level of granularity this gives us without sacrificing extant functionality.
