### ISSUE TITLE
[BUG]-ZoomRoom Selfview FB incorrect

### ISSUE THREAD

**Issue by hunterwbrock** [PepperDash/Essentials#920]
**Was this bug identified in a specific build version?**
1.9.8-beta-1796

**Describe the bug**
In testing ZoomRoom, it was noticed that sometimes the selfview PIP would turn on, and the feedback was incorrectly reporting that the PIP was off.

**To Reproduce**
1. In a call, select the 'Speaker' view from any other view.
- or -
2. In a call and 'Speaker' view selected, with selfview off, engage the selfview pip position toggle.

Either of these actions seemed to engage selfview, but the feedback failed to turn to on.

**Comment by ndorin** [comment]
@hunterwbrock Out of curiosity, I'd like to know if you try the 1.10.0 version released this morning if the issue persists.  There were major updates made to ZoomRoom in that branch that may _possibly_ correct this bug.
