### ISSUE TITLE
[BUG]-Dev branch includes change to IBasicVolumeWithFeedback

### ISSUE THREAD

**Issue by jtalborough** [PepperDash/Essentials#955]
**Was this bug identified in a specific build version?**
At some point there was a change to the PepperDash.Essentials.Core.IBasicVolumeWithFeedback interface that is included in Dev. I believe the pull request #916 is the issue. When using the Dev branch devices using IBasicVolumeWithFeedback will fail. release 1.10.1 seems to be fine. 

```
ERROR: Device DspBridge PostActivation failure: Method not found: get_MuteFeedback PepperDash.Essentials.Core.IBasicVolumeWithFeedback
```

**Comment by andrew-welker** [comment]
What device was throwing this error?

**Comment by jtalborough** [comment]
Its was the Qsc Plugin.

**Comment by TrevorPayne** [comment]
@jtalborough 

This seems to be resolved - can we close it?
