### ISSUE TITLE
[BUG]-ZoomRoom 5.11.0 updates

### ISSUE THREAD

**Issue by ndorin** [PepperDash/Essentials#965]
**Was this bug identified in a specific build version?**
Changes to ZoomRoom v5.11.0.1540 cause issues with Essentials 1.10.2 and earlier.  Appears to be caused by bugs in ZoomRoom API.  Creating this issue for tracking and visibility purposes

**Describe the bug**
* Call/Meeting Status FB doesn't report correctly
* `zCommand Call Info` response from ZoomRoom API is truncated.  We can't get most basic info about the meeting without this response

**Additional context**
[Zoom Developer Forum Issue Report](https://devforum.zoom.us/t/zr-csapi-zcommand-call-info-response-broken-zoomroom-v5-11-0-1540/71619)

**Comment by jtalborough** [comment]
@ndorin Has this been fixed?

**Comment by ndorin** [comment]
Yes. Zoom fixed this as of 5.13
